import React, { useState } from 'react';
import { Match, Player, League, CheckInRecord, ScoreFormat, MatchType } from '../types';
import { LiveScoreboard } from './LiveScoreboard';
import { matchmakingEngine, GeneratedMatchProposal } from '../services/matchmakingEngine';
import { getLocalDate } from '../services/dateService';
import { 
  Activity, 
  Play, 
  PlusCircle, 
  Sparkles, 
  Clock, 
  ShieldCheck, 
  Users, 
  CheckCircle2, 
  ArrowRight,
  Shuffle,
  AlertCircle
} from 'lucide-react';

interface MatchSchedulerProps {
  matches: Match[];
  players: Player[];
  activeLeague: League;
  checkIns: CheckInRecord[];
  onStartGeneratedMatches: (proposals: GeneratedMatchProposal[]) => void;
  onUpdateScore: (matchId: string, teamAScore: number, teamBScore: number, switchedSides?: boolean) => void;
  onFinishMatch: (matchId: string, winnerTeam: 'teamA' | 'teamB') => void;
  onCancelMatch: (matchId: string) => void;
  onCreateManualMatch: (match: Omit<Match, 'id'>) => void;
}

export const MatchScheduler: React.FC<MatchSchedulerProps> = ({
  matches,
  players,
  activeLeague,
  checkIns,
  onStartGeneratedMatches,
  onUpdateScore,
  onFinishMatch,
  onCancelMatch,
  onCreateManualMatch,
}) => {
  const [selectedDate, setSelectedDate] = useState<string>(
    getLocalDate()
  );
  const [showGeneratorModal, setShowGeneratorModal] = useState(false);
  const [showManualModal, setShowManualModal] = useState(false);
  const [selectedFormat, setSelectedFormat] = useState<ScoreFormat>(activeLeague.defaultFormat || 'RACE_42');
  const [allowMixed, setAllowMixed] = useState(true);

  // Time remaining info
  const timeInfo = matchmakingEngine.calculateSessionTimeRemaining(activeLeague);

  // Active / in-progress matches for today
  const activeMatches = matches.filter(
    (m) =>
      m.date === selectedDate &&
      m.leagueId === activeLeague.id &&
      (m.status === 'IN_PROGRESS' || m.status === 'SCHEDULED')
  );

  // Proposals generated by smart algorithm
  const matchmakingResult = matchmakingEngine.generateMatchSchedule(players, checkIns, matches, {
    league: activeLeague,
    date: selectedDate,
    courtsAvailable: activeLeague.courtsCount,
    format: selectedFormat,
    allowMixedDoubles: allowMixed,
    remainingMinutes: timeInfo.remainingMinutes,
  });

  // Manual Form State
  const [manualCourt, setManualCourt] = useState(1);
  const [manualType, setManualType] = useState<MatchType>('MD');
  const [manualFormat, setManualFormat] = useState<ScoreFormat>(activeLeague.defaultFormat || 'RACE_42');
  const [manualP1A, setManualP1A] = useState('');
  const [manualP2A, setManualP2A] = useState('');
  const [manualP1B, setManualP1B] = useState('');
  const [manualP2B, setManualP2B] = useState('');

  const handleCreateManual = (e: React.FormEvent) => {
    e.preventDefault();
    if (!manualP1A || !manualP2A || !manualP1B || !manualP2B) {
      alert('Mohon pilih 4 pemain untuk pertandingan ganda.');
      return;
    }
    const unique = new Set([manualP1A, manualP2A, manualP1B, manualP2B]);
    if (unique.size < 4) {
      alert('Pemain tidak boleh ganda/sama.');
      return;
    }

    onCreateManualMatch({
      leagueId: activeLeague.id,
      seasonId: activeLeague.activeSeasonId,
      date: selectedDate,
      courtNumber: manualCourt,
      matchType: manualType,
      format: manualFormat,
      teamA: { player1Id: manualP1A, player2Id: manualP2A, score: 0 },
      teamB: { player1Id: manualP1B, player2Id: manualP2B, score: 0 },
      status: 'IN_PROGRESS',
      startedAt: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    });

    setShowManualModal(false);
  };

  return (
    <div className="space-y-6">
      {/* Top Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-black text-white flex items-center gap-2.5">
            <Activity className="text-emerald-400" size={26} />
            <span>Jadwal Lapangan & Live Scoring</span>
          </h2>
          <p className="text-xs text-slate-400 mt-0.5">
            {activeLeague.name} • {activeLeague.courtsCount} Lapangan Aktif • Jam {activeLeague.startTime} - {activeLeague.endTime} WIB
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2.5">
          <input
            type="date"
            value={selectedDate}
            onChange={(e) => setSelectedDate(e.target.value)}
            className="text-xs py-2 px-3 rounded-lg bg-slate-900 border-white/10 text-slate-200 w-auto"
          />

          <button
            onClick={() => setShowGeneratorModal(true)}
            className="btn btn-primary btn-sm flex items-center gap-1.5 font-bold shadow-lg shadow-emerald-500/20"
          >
            <Sparkles size={15} />
            <span>Generate Match Otomatis</span>
          </button>

          <button
            onClick={() => setShowManualModal(true)}
            className="btn btn-secondary btn-sm flex items-center gap-1.5"
          >
            <PlusCircle size={15} />
            <span>Buat Partai Manual</span>
          </button>
        </div>
      </div>

      {/* Active Courts Live Board */}
      {activeMatches.length === 0 ? (
        <div className="glass-panel p-12 text-center border-dashed border-white/15">
          <div className="w-16 h-16 rounded-2xl bg-slate-800/80 border border-white/10 flex items-center justify-center mx-auto mb-4 text-emerald-400">
            <Activity size={32} />
          </div>
          <h3 className="text-lg font-bold text-white mb-1">Tidak Ada Pertandingan yang Sedang Berlangsung</h3>
          <p className="text-xs text-slate-400 max-w-md mx-auto mb-6">
            Klik tombol <strong>Generate Match Otomatis</strong> untuk menyusun pasangan ganda seimbang (MD/WD/XD) dari peserta yang telah check-in.
          </p>
          <button
            onClick={() => setShowGeneratorModal(true)}
            className="btn btn-primary btn-md inline-flex items-center gap-2"
          >
            <Sparkles size={16} />
            <span>Susun Jadwal Sekarang</span>
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {activeMatches.map((match) => (
            <LiveScoreboard
              key={match.id}
              match={match}
              players={players}
              onUpdateScore={onUpdateScore}
              onFinishMatch={onFinishMatch}
              onCancelMatch={onCancelMatch}
            />
          ))}
        </div>
      )}

      {/* Modal: Smart Match Generator */}
      {showGeneratorModal && (
        <div className="fixed inset-0 bg-slate-950/85 backdrop-blur-md z-50 flex items-center justify-center p-4 overflow-y-auto">
          <div className="glass-panel max-w-2xl w-full p-6 space-y-5 border border-white/20 shadow-2xl my-8">
            <div className="flex items-center justify-between border-b border-white/10 pb-3">
              <div className="flex items-center gap-2">
                <div className="p-2 rounded-xl bg-emerald-500/20 text-emerald-400">
                  <Sparkles size={20} />
                </div>
                <div>
                  <h3 className="text-lg font-extrabold text-white">Smart Match Generator</h3>
                  <p className="text-xs text-slate-400">Membuat partai seimbang otomatis dari antrean check-in</p>
                </div>
              </div>
              <button
                onClick={() => setShowGeneratorModal(false)}
                className="text-slate-400 hover:text-white text-lg p-1"
              >
                ✕
              </button>
            </div>

            {/* Options Selection */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 bg-slate-900/80 p-4 rounded-xl border border-white/10">
              {/* Format Skor Selection */}
              <div>
                <label className="text-xs font-bold text-slate-300 block mb-1.5">
                  Format Skor Pertandingan:
                </label>
                <div className="grid grid-cols-2 gap-2">
                  <button
                    type="button"
                    onClick={() => setSelectedFormat('RACE_42')}
                    className={`p-2.5 rounded-lg text-xs font-bold border text-center transition ${
                      selectedFormat === 'RACE_42'
                        ? 'bg-amber-500/20 text-amber-300 border-amber-500/50 ring-1 ring-amber-500/30'
                        : 'bg-slate-800 text-slate-400 border-white/5 hover:text-white'
                    }`}
                  >
                    ⚡ Race to 42
                  </button>
                  <button
                    type="button"
                    onClick={() => setSelectedFormat('BWF')}
                    className={`p-2.5 rounded-lg text-xs font-bold border text-center transition ${
                      selectedFormat === 'BWF'
                        ? 'bg-emerald-500/20 text-emerald-300 border-emerald-500/50 ring-1 ring-emerald-500/30'
                        : 'bg-slate-800 text-slate-400 border-white/5 hover:text-white'
                    }`}
                  >
                    🏸 Standar BWF (21)
                  </button>
                </div>
              </div>

              {/* Mixed Doubles Priority Option */}
              <div>
                <label className="text-xs font-bold text-slate-300 block mb-1.5">
                  Prioritas Ganda:
                </label>
                <div className="p-2.5 bg-slate-800/90 rounded-lg border border-white/5 space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-xs text-slate-300 font-medium">Utamakan MD & WD:</span>
                    <span className="text-[11px] bg-emerald-500/20 text-emerald-300 px-2 py-0.5 rounded font-bold">Wajib ✓</span>
                  </div>
                  <label className="flex items-center gap-2 cursor-pointer pt-1 border-t border-white/5">
                    <input
                      type="checkbox"
                      checked={allowMixed}
                      onChange={(e) => setAllowMixed(e.target.checked)}
                      className="w-4 h-4 rounded text-emerald-500 bg-slate-900 border-white/20 focus:ring-0"
                    />
                    <span className="text-xs text-slate-300 font-semibold">
                      Izinkan Ganda Campuran (XD) jika sisa waktu / pemain cukup
                    </span>
                  </label>
                </div>
              </div>
            </div>

            {/* Generated Match Proposals Preview */}
            <div className="space-y-3">
              <h4 className="text-xs font-bold text-slate-300 uppercase tracking-wider flex items-center justify-between">
                <span>Rancangan Partai Pertandingan ({matchmakingResult.proposals.length} Lapangan)</span>
                <span className="text-[11px] text-emerald-400 font-normal">
                  Prioritas: Pemain yang belum main 1x
                </span>
              </h4>

              {matchmakingResult.proposals.length === 0 ? (
                <div className="p-6 bg-slate-900/60 rounded-xl border border-dashed border-white/10 text-center text-xs text-slate-400">
                  <AlertCircle size={20} className="mx-auto mb-2 text-amber-400" />
                  Tidak cukup pemain yang check-in untuk membentuk partai ganda (minimal 4 pemain putra atau 4 pemain putri).
                </div>
              ) : (
                <div className="space-y-3 max-h-72 overflow-y-auto pr-1">
                  {matchmakingResult.proposals.map((prop, idx) => (
                    <div
                      key={idx}
                      className="p-3.5 bg-slate-900/90 rounded-xl border border-white/10 flex flex-col sm:flex-row sm:items-center justify-between gap-3 shadow-md"
                    >
                      <div className="flex items-center gap-3">
                        <div className="w-8 h-8 rounded-lg bg-emerald-500/20 text-emerald-300 font-black flex items-center justify-center font-mono text-xs shrink-0">
                          L{prop.courtNumber}
                        </div>
                        <div>
                          <div className="flex items-center gap-2 mb-1">
                            <span className="text-xs font-bold text-white">
                              {prop.matchType === 'MD' ? 'Ganda Putra' : prop.matchType === 'WD' ? 'Ganda Putri' : 'Ganda Campuran'}
                            </span>
                            <span className="text-[10px] bg-slate-800 text-amber-300 px-2 py-0.5 rounded border border-amber-500/30 font-medium">
                              {prop.balanceScore}
                            </span>
                          </div>
                          <div className="text-xs text-slate-300 flex items-center gap-1.5 flex-wrap">
                            <span className="text-blue-300 font-bold">
                              {prop.teamA.player1.name} (Lvl {prop.teamA.player1.level}) & {prop.teamA.player2.name} (Lvl {prop.teamA.player2.level})
                            </span>
                            <span className="text-slate-500 font-black">VS</span>
                            <span className="text-pink-300 font-bold">
                              {prop.teamB.player1.name} (Lvl {prop.teamB.player1.level}) & {prop.teamB.player2.name} (Lvl {prop.teamB.player2.level})
                            </span>
                          </div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Unmatched Players Notes */}
            {matchmakingResult.unmatchedPlayers.length > 0 && (
              <div className="p-3 bg-amber-500/10 border border-amber-500/30 rounded-xl text-xs text-amber-200/90 flex items-center gap-2">
                <Users size={16} className="text-amber-400 shrink-0" />
                <span>
                  {matchmakingResult.unmatchedPlayers.length} pemain ({matchmakingResult.unmatchedPlayers.map((p) => p.name).join(', ')}) berada di antrean untuk ronde berikutnya.
                </span>
              </div>
            )}

            {/* Actions */}
            <div className="flex items-center justify-end gap-3 pt-3 border-t border-white/10">
              <button
                type="button"
                onClick={() => setShowGeneratorModal(false)}
                className="btn btn-secondary btn-sm"
              >
                Batal
              </button>
              <button
                type="button"
                disabled={matchmakingResult.proposals.length === 0}
                onClick={() => {
                  onStartGeneratedMatches(matchmakingResult.proposals);
                  setShowGeneratorModal(false);
                }}
                className="btn btn-primary btn-sm flex items-center gap-1.5 font-bold shadow-lg shadow-emerald-500/20 disabled:opacity-40"
              >
                <Play size={14} />
                <span>Mulai Pertandingan di Lapangan</span>
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Modal: Manual Match Creator */}
      {showManualModal && (
        <div className="fixed inset-0 bg-slate-950/85 backdrop-blur-md z-50 flex items-center justify-center p-4">
          <form
            onSubmit={handleCreateManual}
            className="glass-panel max-w-lg w-full p-6 space-y-4 border border-white/20 shadow-2xl"
          >
            <div className="flex items-center justify-between border-b border-white/10 pb-3">
              <h3 className="text-lg font-bold text-white flex items-center gap-2">
                <PlusCircle className="text-emerald-400" size={20} />
                <span>Buat Pertandingan Manual</span>
              </h3>
              <button
                type="button"
                onClick={() => setShowManualModal(false)}
                className="text-slate-400 hover:text-white"
              >
                ✕
              </button>
            </div>

            <div className="grid grid-cols-3 gap-3">
              <div>
                <label className="text-xs font-bold text-slate-300 block mb-1">Lapangan:</label>
                <select
                  value={manualCourt}
                  onChange={(e) => setManualCourt(Number(e.target.value))}
                  className="text-xs"
                >
                  {Array.from({ length: activeLeague.courtsCount }).map((_, i) => (
                    <option key={i + 1} value={i + 1}>
                      Lapangan {i + 1}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="text-xs font-bold text-slate-300 block mb-1">Kategori:</label>
                <select
                  value={manualType}
                  onChange={(e) => setManualType(e.target.value as MatchType)}
                  className="text-xs"
                >
                  <option value="MD">Ganda Putra (MD)</option>
                  <option value="WD">Ganda Putri (WD)</option>
                  <option value="XD">Ganda Campuran (XD)</option>
                </select>
              </div>

              <div>
                <label className="text-xs font-bold text-slate-300 block mb-1">Format Skor:</label>
                <select
                  value={manualFormat}
                  onChange={(e) => setManualFormat(e.target.value as ScoreFormat)}
                  className="text-xs"
                >
                  <option value="RACE_42">Race to 42</option>
                  <option value="BWF">Standar BWF (21)</option>
                </select>
              </div>
            </div>

            {/* Tim A */}
            <div className="p-3 bg-slate-900/90 rounded-xl border border-blue-500/30 space-y-2">
              <span className="text-xs font-bold text-blue-400 block">TIM A:</span>
              <div className="grid grid-cols-2 gap-2">
                <select
                  value={manualP1A}
                  onChange={(e) => setManualP1A(e.target.value)}
                  className="text-xs"
                  required
                >
                  <option value="">Pilih Pemain 1</option>
                  {players.map((p) => (
                    <option key={p.id} value={p.id}>
                      {p.name} ({p.gender === 'pria' ? 'P' : 'W'} - Lvl {p.level})
                    </option>
                  ))}
                </select>

                <select
                  value={manualP2A}
                  onChange={(e) => setManualP2A(e.target.value)}
                  className="text-xs"
                  required
                >
                  <option value="">Pilih Pemain 2</option>
                  {players.map((p) => (
                    <option key={p.id} value={p.id}>
                      {p.name} ({p.gender === 'pria' ? 'P' : 'W'} - Lvl {p.level})
                    </option>
                  ))}
                </select>
              </div>
            </div>

            {/* Tim B */}
            <div className="p-3 bg-slate-900/90 rounded-xl border border-pink-500/30 space-y-2">
              <span className="text-xs font-bold text-pink-400 block">TIM B:</span>
              <div className="grid grid-cols-2 gap-2">
                <select
                  value={manualP1B}
                  onChange={(e) => setManualP1B(e.target.value)}
                  className="text-xs"
                  required
                >
                  <option value="">Pilih Pemain 1</option>
                  {players.map((p) => (
                    <option key={p.id} value={p.id}>
                      {p.name} ({p.gender === 'pria' ? 'P' : 'W'} - Lvl {p.level})
                    </option>
                  ))}
                </select>

                <select
                  value={manualP2B}
                  onChange={(e) => setManualP2B(e.target.value)}
                  className="text-xs"
                  required
                >
                  <option value="">Pilih Pemain 2</option>
                  {players.map((p) => (
                    <option key={p.id} value={p.id}>
                      {p.name} ({p.gender === 'pria' ? 'P' : 'W'} - Lvl {p.level})
                    </option>
                  ))}
                </select>
              </div>
            </div>

            <div className="flex items-center justify-end gap-2 pt-2">
              <button
                type="button"
                onClick={() => setShowManualModal(false)}
                className="btn btn-secondary btn-sm"
              >
                Batal
              </button>
              <button type="submit" className="btn btn-primary btn-sm font-bold">
                Jadwalkan Partai
              </button>
            </div>
          </form>
        </div>
      )}
    </div>
  );
};
